# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/igw1k9zpn8yjkgaj0cxqvcs5h3qz0h7k-hm-session-vars.fish

/nix/store/bz5jc3dkvj4952qqrc3fhrs9x5n7n0r0-mcfly-0.9.2/bin/mcfly init fish | source


status is-login; and begin

    # Login shell initialisation


end

status is-interactive; and begin

    # Abbreviations
    abbr --add -- cat bat
    abbr --add -- cd z
    abbr --add -- ls 'eza -l --icons=always'
    abbr --add -- lsblk 'lsblk -o NAME,LABEL,SIZE,FSTYPE,FSUSED,MOUNTPOINT'

    # Aliases
    alias la 'eza -a'
    alias ll 'eza -l'
    alias lla 'eza -la'
    alias ls eza
    alias lt 'eza --tree'

    # Interactive shell initialisation
    /nix/store/2f27qfzb3b3s09rjfz0g06g03igibnx1-fzf-0.55.0/bin/fzf --fish | source

    set fish_greeting # Disable greeting

    /nix/store/w1w714ssyrqnzlwnvdqqdhrdpnnxybxg-zoxide-0.9.5/bin/zoxide init fish | source

    function y
        set tmp (mktemp -t "yazi-cwd.XXXXX")
        yazi $argv --cwd-file="$tmp"
        if set cwd (cat -- "$tmp"); and [ -n "$cwd" ]; and [ "$cwd" != "$PWD" ]
            builtin cd -- "$cwd"
        end
        rm -f -- "$tmp"
    end

    if test "$TERM" != dumb
        eval (/home/thulashitharan/.nix-profile/bin/starship init fish)

    end

    if set -q KITTY_INSTALLATION_DIR
        set --global KITTY_SHELL_INTEGRATION no-rc
        source "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish"
        set --prepend fish_complete_path "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_completions.d"
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/thulashitharan/.local/share/fish/home-manager_generated_completions" $post
    end

    /nix/store/823qi3acdfxnvn0ylygjg6jabx7b4q31-direnv-2.34.0/bin/direnv hook fish | source


end
